name: Pull Request
on:
    pull_request

jobs:
    build:
        name: Build Application
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout

            - uses: actions/cache@v3
              name: Cache application
              with:
                path: node_modules
                key: ${{runner.os}}-${{hashFiles('**/package-lock')}}

            - name: Install dependencies
              run: npm install

    codigoMorto:
        needs: build
        name: Limpa codigo nao usa
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout

            - uses: actions/cache@v3
              name: Cache application
              with:
                path: node_modules
                key: ${{runner.os}}-${{hashFiles('**/package-lock.json')}}

            - name: Run ts-prone
              run: npm run ts-pune 
            

    